{
  description = "My NixOS configurations";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { nixpkgs, disko, home-manager, ... }: {
    # nixos-anywhere --flake .#ulthc --generate-hardware-config nixos-generate-config ./hosts/ulthc/hardware-configuration.nix <hostname>
    nixosConfigurations.ulthc = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
          disko.nixosModules.disko
          ./hosts/ulthc/configuration.nix
          ./hosts/ulthc/disko-config.nix
          ./hosts/ulthc/hardware-configuration.nix # autogenerated and not committed
        ];
    };
    
  };
}
